config/routes.rb
Rails.application.routes.draw do
  get '/', to: "home#index", as: "home"
  get 'home/index'
  get "home/welcome", to: "home#welcome", as: :user_root
  get "home/welcome", to: "home#welcome", as: "welcome"
  get "home/claims", to: "home#claims", as: "claims"
  get "home/coverage", to: "home#coverage", as: "coverage"
  get "admin/view_users", to: "admin#view_users"
  
  
  devise_for :users
  get "/admin/index", to: "admin#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/claim.rb
class Claim < ApplicationRecord
	belongs_to: user
end

app/models/insurance.rb
class Insurance < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :claim
  has_many :insurances
  def admin?
  	return role_id == 99
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
	before_action :authenticate_user!
	before_action :admin_only!
		
	def index
	end

	def view_users
		@users = User.all
	end

	private

	def admin_only!
		if !current_user.admin?
			redirect_to "/"
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def claims
	@users = User.all
  end
  
  def index
  end
  

  
  def coverage
	@users = User.all
  end
end

app/controllers/insurances_controller.rb
class InsurancesController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/insurances_helper.rb
module InsurancesHelper
end

app/views/admin/index.html.erb
    <main role="main" class="container">

      <div class="starter-template">
        <h1>Bootstrap starter template</h1>
        <p class="lead">Use this document as a way to quickly start any new project.<br> All you get is this text and a mostly barebones HTML document.</p>
      </div>

    </main><!-- /.container -->

app/views/home/claims.html.erb
<!DOCTYPE html>
<html>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link href="https://fonts.googleapis.com/css?family=Raleway" rel="stylesheet">
<style>
* {
  box-sizing: border-box;
}

body {
  background-color: #f1f1f1;
}

#regForm {
  background-color: #ffffff;
  margin: 100px auto;
  font-family: Raleway;
  padding: 40px;
  width: 70%;
  min-width: 300px;
}

h1 {
  text-align: center;  
}

input {
  padding: 10px;
  width: 100%;
  font-size: 17px;
  font-family: Raleway;
  border: 1px solid #aaaaaa;
}

/* Mark input boxes that gets an error on validation: */
input.invalid {
  background-color: #ffdddd;
}

/* Hide all steps by default: */
.tab {
  display: none;
}

button {
  background-color: #4CAF50;
  color: #ffffff;
  border: none;
  padding: 10px 20px;
  font-size: 17px;
  font-family: Raleway;
  cursor: pointer;
}

button:hover {
  opacity: 0.8;
}

#prevBtn {
  background-color: #bbbbbb;
}

/* Make circles that indicate the steps of the form: */
.step {
  height: 15px;
  width: 15px;
  margin: 0 2px;
  background-color: #bbbbbb;
  border: none;  
  border-radius: 50%;
  display: inline-block;
  opacity: 0.5;
}

.step.active {
  opacity: 1;
}

/* Mark the steps that are finished and valid: */
.step.finish {
  background-color: #4CAF50;
}
</style>
<body>

<h3><center>Your Insurance Claims</center></h3>
<table class="table table-bordered table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Claim</th>
    </tr>
  </thead>
  <tbody>
	</tbody>
</table>


<form id="regForm" action="/action_page.php">
  <h1>Start A New Claim:</h1>
  <!-- One "tab" for each step in the form: -->
  <div class="tab">Accident Date, Time And Location:
    <p><input placeholder="Date..." oninput="this.className = ''" name="date"></p>
    <p><input placeholder="Time..." oninput="this.className = ''" name="time"></p>
    <p><input placeholder="Location..." oninput="this.className = ''" name="loc"></p>  
  </div>
  <div class="tab">Police Report:
    <p><input placeholder="If filed, type yes; else, leave all boxes blank..." oninput="this.className = ''" name="report"></p>
    <p><input placeholder="Police officer name..." oninput="this.className = ''" name="off_name"></p>
	<p><input placeholder="Agency..." oninput="this.className = ''" name="off_agen"></p>
	<p><input placeholder="Report number..." oninput="this.className = ''" name="report_num"></p>
  </div>
  <div class="tab">Add URLs Of Pictures Taken After Accident:
	<p><input placeholder="URL goes here..." oninput="this.className = ''" name="url"></p>
  </div>
  <div class="tab">Other Driver's Information:
    <p><input placeholder="Name of other driver..." oninput="this.className = ''" name="other_name"></p>
    <p><input placeholder="Driver License of driver..." oninput="this.className = ''" name="other_license"></p>
	<p><input placeholder="Insurance name of other driver..." oninput="this.className = ''" name="other_insurance"></p>
    <p><input placeholder="License plate number of driver's vehicle..." oninput="this.className = ''" name="other_plate"></p>
	<p><input placeholder="Address of driver..." oninput="this.className = ''" name="other_address"></p>
    <p><input placeholder="State driver lives in ..." oninput="this.className = ''" name="other_state"></p>
    <p><input placeholder="City driver lives in..." oninput="this.className = ''" name="other_city"></p>
    <p><input placeholder="Zip code..." oninput="this.className = ''" name="other_zip"></p>
    <p><input placeholder="Telephone number of driver..." oninput="this.className = ''" name="other_telephone"></p>

  </div>
  <div style="overflow:auto;">
    <div style="float:right;">
      <button type="button" id="prevBtn" onclick="nextPrev(-1)">Previous</button>
      <button type="button" id="nextBtn" onclick="nextPrev(1)">Next</button>
    </div>
  </div>
  <!-- Circles which indicates the steps of the form: -->
  <div style="text-align:center;margin-top:40px;">
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
    <span class="step"></span>
  </div>
</form>

<script>
var currentTab = 0; // Current tab is set to be the first tab (0)
showTab(currentTab); // Display the crurrent tab

function showTab(n) {
  // This function will display the specified tab of the form...
  var x = document.getElementsByClassName("tab");
  x[n].style.display = "block";
  //... and fix the Previous/Next buttons:
  if (n == 0) {
    document.getElementById("prevBtn").style.display = "none";
  } else {
    document.getElementById("prevBtn").style.display = "inline";
  }
  if (n == (x.length - 1)) {
    document.getElementById("nextBtn").innerHTML = "Submit";
  } else {
    document.getElementById("nextBtn").innerHTML = "Next";
  }
  //... and run a function that will display the correct step indicator:
  fixStepIndicator(n)
}

function nextPrev(n) {
  // This function will figure out which tab to display
  var x = document.getElementsByClassName("tab");
  // Exit the function if any field in the current tab is invalid:
  if (n == 1 && !validateForm()) return false;
  // Hide the current tab:
  x[currentTab].style.display = "none";
  // Increase or decrease the current tab by 1:
  currentTab = currentTab + n;
  // if you have reached the end of the form...
  if (currentTab >= x.length) {
    // ... the form gets submitted:
    return false;
  }
  // Otherwise, display the correct tab:
  showTab(currentTab);
}

function validateForm() {
  // This function deals with validation of the form fields
  var x, y, i, valid = true;
  x = document.getElementsByClassName("tab");
  y = x[currentTab].getElementsByTagName("input");
  // A loop that checks every input field in the current tab:
  for (i = 0; i < y.length; i++) {
    // If a field is empty...
    if (y[i].value == "") {
      // add an "invalid" class to the field:
      y[i].className += " invalid";
      // and set the current valid status to false
      valid = false;
    }
  }
  // If the valid status is true, mark the step as finished and valid:
  if (valid) {
    document.getElementsByClassName("step")[currentTab].className += " finish";
  }
  return valid; // return the valid status
}

function fixStepIndicator(n) {
  // This function removes the "active" class of all steps...
  var i, x = document.getElementsByClassName("step");
  for (i = 0; i < x.length; i++) {
    x[i].className = x[i].className.replace(" active", "");
  }
  //... and adds the "active" class on the current step:
  x[n].className += " active";
}
</script>

</body>
</html>

app/views/home/coverage.html.erb
<h3><center>Your Insurances</center></h3>
<table class="table table-bordered table-striped">
  <thead class="thead-inverse">
    <tr>
      <th>#</th>
      <th>Insurance</th>
	  <th>Vehicle(s) Covered</th>
	  <th>Driver(s) Covered</th>
    </tr>
  </thead>
  <tbody>
  </tbody>
</table>

app/views/home/index.html.erb
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Business Frontpage - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/business-frontpage.css" rel="stylesheet">

  </head>

  <body>
    <!-- Header with Background Image -->
    <header class="business-header">
      <div class="container">
        <div class="row">
          <div class="col-lg-12">
            <h1 class="display-3 text-center text-black mt-4"><bold>MyCrashBox</bold></h1>
          </div>
        </div>
      </div>
    </header>

    <!-- Page Content -->
    <div class="container">

      <div class="row">
        <div class="col-sm-8">
          <h2 class="mt-4">What We Do</h2>
          <p>MyCrashBox is an automotive insurance manager that keeps track of the claims you make, helps you make them so that you can get the most of your claim and keeps track of the automotive insurances you have! </p>
          <p>MyCrashBox is the only website that holds all your insurances together so you don't have to look around for your old insurance papers to see who's covered! We do the digging!</p>
          <p>
            <%= link_to 'Sign Up!', new_user_registration_path, :class => 'btn btn-primary'%>
          </p>
        </div>
        <div class="col-sm-4">
          <h2 class="mt-4">Contact Us</h2>
          <address>
            <br>3481 Melrose Place
            <br>Beverly Hills, CA 90210
            <br>
          </address>
          <address>
            <abbr title="Phone">P:</abbr>
            (123) 456-7890
            <br>
            <abbr title="Email">E:</abbr>
            <a href="mailto:#">mycrashbox@gmail.com</a>
          </address>
        </div>
      </div>
      <!-- /.row -->

      <div class="row">
        <div class="col-sm-4 my-4">
          <div class="card">
            <img class="card-img-top" src="https://rac.com.au/-/media/images/rac-website/tile-images/images/car-motoring/insurance/car_crash_rs.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title">Had An Accident?</h4>
              <p class="card-text">Sign up with MyCrashBox to make your claims more managable and let us walk you through what you need! With MyCrashBox, anyone can easily make a claim and get the most out of their insurances!</p>
            </div>
            <div class="card-footer">
              <%= link_to 'Make Claims Simple!', new_user_registration_path, :class => 'btn btn-primary'%>
            </div>
          </div>
        </div>
        <div class="col-sm-4 my-4">
          <div class="card">
            <img class="card-img-top" src="http://www.powerfundingllc.com/wp-content/uploads/2014/11/moneyman-e1415384696380.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title">Want More From Your Insurance?</h4>
              <p class="card-text">With MyCrashBox, you are able to make the most out of your insurance claims by always having the right information as you follow our steps in making your successful claims! Don't let insurance hold you back from the money you deserve!</p>
            </div>
            <div class="card-footer">
              <%= link_to 'Claim Your Money!', new_user_registration_path, :class => 'btn btn-primary'%>
            </div>
          </div>
        </div>
        <div class="col-sm-4 my-4">
          <div class="card">
            <img class="card-img-top" src="https://sellleadsucceed.files.wordpress.com/2013/03/bigstock-happy-mature-business-man-offe-20200724.jpg" alt="">
            <div class="card-body">
              <h4 class="card-title">We Manage, You Save!</h4>
              <p class="card-text">MyCrashBox manages all of your automotive insurances so you can stop looking around for all your insurance information! We even take you a step-by-step process on how to easily make a perfect insurance claim every single time so you can save big bucks!</p>
            </div>
            <div class="card-footer">
              <%= link_to 'Save Now!', new_user_registration_path, :class => 'btn btn-primary'%>
            </div>
          </div>
        </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MyCrashBox 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

app/views/home/welcome.html.erb
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Heroic Features - Start Bootstrap Template</title>

    <!-- Bootstrap core CSS -->
    <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="css/heroic-features.css" rel="stylesheet">

  </head>

  <body>

   

    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3">Welcome!</h1>
        <p class="lead">Greetings and welcome to your CrashBox! Your CrashBox stores all your insurance information for your automotives and keeps track of all the claims you've processed or are about to process! We keep your things tidy in here so that you can keep things tidy out there!</p>
      </header>

      <!-- Page Features -->
      <div class="row text-center">

        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Start A Claim!</h4>
              <p class="card-text">Automotive accidents are the worse but making an insurance claim makes it even worse. Let's keep track of what you need to make the most out of your claim!</p>
            </div>
            <div class="card-footer">
              <%= link_to "Let's Get Things Going!", claims_path, :class=>"btn btn-primary"%>
            </div>
          </div>
        </div>

        <div class="col-lg-3 col-md-6 mb-4">
          <div class="card">
            <div class="card-body">
              <h4 class="card-title">Check Out Your Insurances!</h4>
              <p class="card-text">Let's keep track of what is insured and who is covered! You add and edit the insurances you have to make things a lot more manageable!</p>
            </div>
            <div class="card-footer">
              <%= link_to "Check It Out!", coverage_path, :class=>"btn btn-primary"%>
            </div>
          </div>
        </div>
      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->

    <!-- Footer -->
    <footer class="py-5 bg-dark">
      <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; MyCrashBox 2017</p>
      </div>
      <!-- /.container -->
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

  </body>

app/views/layouts/_navigation.html.erb
    <nav class="navbar navbar-expand-md navbar-dark bg-dark">
		  <% if user_signed_in? %>
		  <li>
            <%= link_to "MyCrashBox", welcome_path, :class => 'navbar-brand'%>
          </li>
		  <% else %>
		  <li>
            <%= link_to "MyCrashBox", home_path, :class => 'navbar-brand'%>
          </li>
		  <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarsExampleDefault">
        <ul class="navbar-nav mr-auto">
          <% if user_signed_in? %>
		  <li class="nav-item">
            <%= link_to 'Home', welcome_path, :class => 'nav-link'%>
          </li>
		  <% else %>
		  <li class="nav-item">
            <%= link_to 'Home', home_path, :class => 'nav-link'%>
          </li>
		  <% end %>
		  
			<% if user_signed_in? %>
			  <li class="nav-item">
			  <%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'nav-link'%>       
			  </li>
			<% else %>
			  <li class="nav-item">
			  <%= link_to 'Login', new_user_session_path, :class => 'nav-link'%>  
			  </li>
			<% end %>

			<% if user_signed_in? %>
			  <li class="nav-item">
				<%= link_to 'Edit Account', edit_user_registration_path, :class => 'nav-link'%>
			  </li>
			  <li class="nav-item dropdown">
				<a class="nav-link dropdown-toggle" href="http://example.com" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Get Started!</a>
				<div class="dropdown-menu" aria-labelledby="dropdown01">
				  <%= link_to "Your Insurance Claims", claims_path, :class => 'dropdown-item'%>
				  <%= link_to "Your Insurance Coverage", coverage_path, :class => 'dropdown-item'%>
				</div>
			  </li>
			<% else %>
			  <li class="nav-item">
				<%= link_to 'Sign Up', new_user_registration_path, :class => 'nav-link'%>
			  </li>
			<% end %>
        </ul>
		
		<% if user_signed_in? %>
		  <li class="navbar-brand">Hello,<%= current_user.email %>!</li>
		<% end %>
		
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCrashBox</title>
    <%= csrf_meta_tags %>

	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
  	<%= render "layouts/navigation" %> 

    <%= yield %>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </body>
</html>